✨ languageSettings出力
traP-jp/traO-Judge-docs pull request #175
Opened 2024-12-16 06:49 UTC by Kentaro1043

## issue
close #137

## チェックリスト(nix)
- [ ] ビルドが通る
- [ ] license-check.shが通る

2024-12-16 06:51 UTC, Kentaro1043 commented
現状の仕様
コマンド: `nix build .#languageSettings --out-link result.json`
```json
[
	{
		"languages": [
			{
				"binName": "python3.11",
				"compile": "cp \"$SRC\" \"$DIST\"",
				"name": "Python3.11",
				"run": "exec /nix/store/n3qp3gs2jalcfaas2cgagnj4jms4jbza-python3-3.11.10-env/bin/python \"$DIST\""
			}
		]
	},
	{
		"languages": [
			{
				"binName": "python3.12",
				"compile": "cp \"$SRC\" \"$DIST\"",
				"name": "Python3.12",
				"run": "exec /nix/store/hsbs4k9znhf3sz35n1c8xmncf4k0jmp7-python3-3.12.6-env/bin/python \"$DIST\""
			}
		]
	},
	{
		"languages": [
			{
				"binName": "python3.12-quantum",
				"compile": "cp \"$SRC\" \"$DIST\"",
				"libraries": [
					{
						"name": "qiskit",
						"version": "1.2.4"
					},
					{
						"name": "numpy",
						"version": "2.1.3"
					},
					{
						"name": "scipy",
						"version": "1.14.1"
					},
					{
						"name": "networkx",
						"version": "3.4.2"
					},
					{
						"name": "sympy",
						"version": "1.13.3"
					},
					{
						"name": "sortedcontainers",
						"version": "2.4.0"
					},
					{
						"name": "more-itertools",
						"version": "10.5.0"
					},
					{
						"name": "shapely",
						"version": "2.0.6"
					},
					{
						"name": "bitarray",
						"version": "3.0.0"
					},
					{
						"name": "pulp",
						"version": "2.9.0"
					},
					{
						"name": "mpmath",
						"version": "1.3.0"
					},
					{
						"name": "pandas",
						"version": "2.2.3"
					},
					{
						"name": "z3-solver",
						"version": "4.13.3.0"
					},
					{
						"name": "scikit-learn",
						"version": "1.5.2"
					}
				],
				"name": "Python3.12-quantum",
				"run": "exec /nix/store/fdywml2llg5wl1l4d665j0amgmafqd0r-hello-world-env/bin/python \"$DIST\""
			}
		]
	}
]
```

2024-12-16 10:10 UTC, comavius requested changes
https://github.com/traP-jp/traO-Judge-docs/blob/develop/exec-container/schema.json
を参照してjson schemaのバリデーションをしたいです:pray:

2024-12-16 13:27 UTC, comavius commented
こうなってほしいはず
```json
{
  "languages": [
    {
      "binName": "python3.11",
      "compile": "cp \"$SRC\" \"$DIST\"",
      "name": "Python3.11",
      "run": "exec /nix/store/n3qp3gs2jalcfaas2cgagnj4jms4jbza-python3-3.11.10-env/bin/python \"$DIST\""
    },
    {
      "binName": "python3.12",
      "compile": "cp \"$SRC\" \"$DIST\"",
      "name": "Python3.12",
      "run": "exec /nix/store/hsbs4k9znhf3sz35n1c8xmncf4k0jmp7-python3-3.12.6-env/bin/python \"$DIST\""
    },
    {
      "binName": "python3.12-quantum",
      "compile": "cp \"$SRC\" \"$DIST\"",
      "libraries": [
        {
          "name": "qiskit",
          "version": "1.2.4"
        },
        {
          "name": "numpy",
          "version": "2.1.3"
        },
        {
          "name": "scipy",
          "version": "1.14.1"
        },
        {
          "name": "networkx",
          "version": "3.4.2"
        },
        {
          "name": "sympy",
          "version": "1.13.3"
        },
        {
          "name": "sortedcontainers",
          "version": "2.4.0"
        },
        {
          "name": "more-itertools",
          "version": "10.5.0"
        },
        {
          "name": "shapely",
          "version": "2.0.6"
        },
        {
          "name": "bitarray",
          "version": "3.0.0"
        },
        {
          "name": "pulp",
          "version": "2.9.0"
        },
        {
          "name": "mpmath",
          "version": "1.3.0"
        },
        {
          "name": "pandas",
          "version": "2.2.3"
        },
        {
          "name": "z3-solver",
          "version": "4.13.3.0"
        },
        {
          "name": "scikit-learn",
          "version": "1.5.2"
        }
      ],
      "name": "Python3.12-quantum",
      "run": "exec /nix/store/fdywml2llg5wl1l4d665j0amgmafqd0r-hello-world-env/bin/python \"$DIST\""
    }
  ]
}
```

2024-12-16 13:47 UTC, comavius commented
json schemaが良くないかも

2024-12-21 10:58 UTC, Kentaro1043 commented
`nix build .#languageSettings`をすれば、`result`にjsonファイルが出てきます。
憂慮事項は、
- 出力されるjsonが1行に全てまとまっているので、フォーマットが必要ならする
といった感じです。

2024-12-21 14:41 UTC, comavius approved these changes
よさそうです、ありがとう！

2024-12-21 14:44 UTC, comavius requested changes
ごめん、compilersも出力できるようにお願いします

2024-12-21 14:47 UTC, comavius commented
> ごめん、compilersも出力できるようにお願いします

これでコードが大きくなりすぎたら関数として切り分けて、`allpkgs.nix`みたいにファイルを分けてほしいかも

2024-12-23 13:48 UTC, Kentaro1043 commented
レビューリクエスト後に申し訳無いですが、ファイル分割もやっておきました

2024-12-24 04:10 UTC, comavius approved these changes
よさそう、ありがとう！

2024-12-24 04:22 UTC, merged