add:openapi.yaml
traP-jp/traO-Judge-docs pull request #30
Opened 2024-10-08 14:04 UTC by mathsuky

close #3
ファイル名と配置が適切ではないかもしれないです

2024-10-08 14:12 UTC, comavius commented
ありがとう

2024-10-08 14:12 UTC, comavius commented
ファイル名は見ればわかりそうなのでそのままで大丈夫です

2024-10-08 14:14 UTC, comavius requested changes
https://github.com/traP-jp/traO-Judge-backend/blob/develop/docs/openapi-ui.Dockerfile もdocsのリポジトリに方に移してほしいです

2024-10-10 01:22 UTC, comavius commented
あと、前回伝え忘れてしまったのですが、back-judge間のものと同じようなCIの追加もお願いします。

2024-10-10 01:22 UTC, comavius requested changes

2024-10-10 01:22 UTC, comavius commented on api/backend/frontend-backend.yaml
> +        content: {}
openapi generatorを動かしたところここがエラーを起こしているので修正をお願いします。

2024-10-10 01:22 UTC, comavius commented on api/backend/frontend-backend.yaml
> +        content: {}
174行目と同じエラーが出ています。

2024-10-10 01:48 UTC, kenken714 commented
contentが空だとエラーを起こしてしまいます

2024-10-10 12:42 UTC, mathsuky commented
すみません，これがよくわかってないです。back-judge間のもの，はどこを参照すれば見つかりますか？
https://github.com/traP-jp/traO-Judge-docs/pull/30#issuecomment-2403712016

2024-10-10 15:16 UTC, comavius commented
.github/workflowにyamlが入っています

2024-10-11 11:16 UTC, mathsuky commented
ありがとうございます！作業してコミット出します

2024-10-12 10:56 UTC, mathsuky commented
追加しました。遅くなり申し訳ございません。お手隙の際に再レビューお願いいたします。

2024-10-14 04:23 UTC, comavius approved these changes
lgtm

2024-10-14 04:28 UTC, merged